# Windows build and test of lager

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cinst rebar3

build: off

test_script:
  - rebar3 eunit

deploy: false
